export var jsonCustomRouteSegments = `[
    {"Route":"2015 uci worlds course","Segment": "Governor St Climb","Start": "15.3km"},
    {"Route":"2019 worlds harrogate circuit","Segment": "Otley Rd Climb","Start": "0.4km"},
    {"Route":"2022 bambino fondo","Segment": "Dirty Sorpresa Climb","Start": "4.9km"},
    {"Route":"2022 bambino fondo","Segment": "Epic KOM Reverse - Start to Jungle Intersection","Start": "9.4km"},
    {"Route":"2022 cycling esports world championships route","Segment": "East Side Drive Climb","Start": "18.0km"},
    {"Route":"2022 cycling esports world championships route","Segment": "Harlem Hill Climb","Start": "25.6km"},
    {"Route":"2022 cycling esports world championships route","Segment": "Harlem Hill Climb","Start": "3.1km"},
    {"Route":"2022 cycling esports world championships route","Segment": "East Side Drive Climb","Start": "40.6km"},
    {"Route":"2022 cycling esports world championships route","Segment": "Harlem Hill Climb","Start": "48.3km"},
    {"Route":"2022 gran fondo","Segment": "Dirty Sorpresa Climb","Start": "4.9km"},
    {"Route":"2022 gran fondo","Segment": "Dirty Sorpresa Climb","Start": "82.5km"},
    {"Route":"2022 gran fondo","Segment": "Epic KOM Reverse - Start to Jungle Intersection","Start": "9.4km"},
    {"Route":"2022 medio fondo","Segment": "Dirty Sorpresa Climb","Start": "4.9km"},
    {"Route":"2022 medio fondo","Segment": "Epic KOM Reverse - Start to Jungle Intersection","Start": "9.4km"},
    {"Route":"astoria line 8","Segment": "East Side Drive Climb","Start": "4.2km"},
    {"Route":"bambino fondo","Segment": "Epic KOM Reverse - Start to Jungle Intersection","Start": "24.4km"},
    {"Route":"bambino fondo","Segment": "Jungle Climb","Start": "32.7km"},
    {"Route":"bambino fondo","Segment": "Jungle to Windmill Climb","Start": "36.5km"},
    {"Route":"beach island loop","Segment": "Dirty Sorpresa Climb","Start": "4.9km"},
    {"Route":"big flat 8","Segment": "Dirty Sorpresa Climb","Start": "20.8km"},
    {"Route":"big loop","Segment": "Jungle Climb","Start": "25.6km"},
    {"Route":"big loop","Segment": "Jungle to Windmill Climb","Start": "30.3km"},
    {"Route":"big loop reverse","Segment": "Jungle CCW Climb","Start": "18.0km"},
    {"Route":"big loop reverse","Segment": "Jungle to Windmill Climb","Start": "21.1km"},
    {"Route":"big loop reverse","Segment": "Dirty Sorpresa Climb","Start": "4.9km"},
    {"Route":"big loop reverse","Segment": "Epic KOM Reverse - Start to Jungle Intersection","Start": "9.0km"},
    {"Route":"bigger loop","Segment": "Jungle Climb","Start": "36.5km"},
    {"Route":"bigger loop","Segment": "Jungle to Windmill Climb","Start": "40.4km"},
    {"Route":"braekfast crits and grits","Segment": "Castle Loop Climb","Start": "10.1km"},
    {"Route":"bridges and boardwalks","Segment": "Festival Harbor Climb CW","Start": "3.0km"},
    {"Route":"cobbled climbs","Segment": "Governor St Climb","Start": "8.3km"},
    {"Route":"cobbled climbs reverse","Segment": "E Main St Climb","Start": "6.5km"},
    {"Route":"country to coastal","Segment": "Festival Harbor Climb CCW","Start": "18.0km"},
    {"Route":"country to coastal","Segment": "Connector Canyon Climb","Start": "26.5km"},
    {"Route":"douce france","Segment": "Les Intestins - Outbound","Start": "0.6km"},
    {"Route":"dust in the wind","Segment": "Epic KOM Reverse - Start to Jungle Intersection","Start": "13.6km"},
    {"Route":"dust in the wind","Segment": "Jungle Climb","Start": "21.4km"},
    {"Route":"dust in the wind","Segment": "Jungle to Windmill Climb","Start": "26.6km"},
    {"Route":"everything bagel","Segment": "East Side Sky Loop Climb","Start": "19.2km"},
    {"Route":"fine and sandy","Segment": "Mech Isle Climb CW","Start": "1.3km"},
    {"Route":"fine and sandy","Segment": "Mech Isle Climb CW","Start": "7.9km"},
    {"Route":"four horsemen","Segment": "Jungle Climb","Start": "74.9km"},
    {"Route":"four horsemen","Segment": "Jungle to Windmill Climb","Start": "78.8km"},
    {"Route":"glyph heights","Segment": "The Grade KOM - Upper Portion","Start": "12.8km"},
    {"Route":"gran fondo","Segment": "Dirty Sorpresa Climb","Start": "26.8km"},
    {"Route":"gran fondo","Segment": "Epic KOM Reverse - Start to Jungle Intersection","Start": "30.8km"},
    {"Route":"gran fondo","Segment": "Jungle CCW Climb","Start": "39.9km"},
    {"Route":"gran fondo","Segment": "Jungle to Windmill Climb","Start": "43.0km"},
    {"Route":"greater london 8","Segment": "Northumberland Ave Climb","Start": "3.6km"},
    {"Route":"greater london flat","Segment": "Northumberland Ave Climb","Start": "3.6km"},
    {"Route":"greater london loop","Segment": "Northumberland Ave Climb","Start": "3.6km"},
    {"Route":"greatest london flat","Segment": "Northumberland Ave Climb","Start": "27.1km"},
    {"Route":"greatest london flat","Segment": "Northumberland Ave Climb","Start": "3.6km"},
    {"Route":"greatest london loop","Segment": "Northumberland Ave Climb","Start": "3.6km"},
    {"Route":"harrogate circuit reverse","Segment": "Kent Rd Climb to Sprint Banner","Start": "1.5km"},
    {"Route":"harrogate circuit reverse","Segment": "Otley Road Kicker (West Bound)","Start": "11.15km"},
    {"Route":"harrogate circuit reverse","Segment": "Climb up from Oak Beck","Start": "6.1km"},
    {"Route":"harrogate circuit reverse","Segment": "Pot Bank Climb","Start": "8.5km"},
    {"Route":"island hopper","Segment": "Mech Isle Climb CW","Start": "6.5km"},
    {"Route":"island hopper","Segment": "Festival Harbor Climb CCW","Start": "8.1km"},
    {"Route":"island outskirts","Segment": "Festival Harbor Climb CCW","Start": "1.4km"},
    {"Route":"jungle circuit","Segment": "Jungle Climb","Start": "6.3km"},
    {"Route":"jungle circuit reverse","Segment": "Jungle CCW Climb","Start": "7.0km"},
    {"Route":"keith hill after party","Segment": "Northumberland Ave Climb","Start": "3.6km"},
    {"Route":"keith hill after party","Segment": "Northumberland Ave Climb","Start": "3.6km"},
    {"Route":"knickerbocker","Segment": "East Side Drive Climb","Start": "17.9km"},
    {"Route":"knickerbocker","Segment": "Harlem Hill Climb","Start": "3.1km"},
    {"Route":"knickerbocker reverse","Segment": "East Side Drive Climb","Start": "19.8km"},
    {"Route":"knickerbocker reverse","Segment": "Harlem Hill Climb","Start": "4.9km"},
    {"Route":"la reine","Segment": "Les Intestins - Outbound","Start": "0.6km"},
    {"Route":"la reine","Segment": "Petit KOM Banner to La Reine","Start": "10.88km"},
    {"Route":"leith hill after party","Segment": "Northumberland Ave Climb","Start": "3.6km"},
    {"Route":"london 8","Segment": "Northumberland Ave Climb","Start": "3.6km"},
    {"Route":"london loop","Segment": "Northumberland Ave Climb","Start": "3.6km"},
    {"Route":"makuri 40","Segment": "Festival Harbor Climb CW","Start": "25.6km"},
    {"Route":"makuri 40","Segment": "Connector Canyon Climb","Start": "33.2km"},
    {"Route":"makuri pretzel","Segment": "Pain Cavern Climb","Start": "33.2km"},
    {"Route":"makuri pretzel","Segment": "Festival Harbor Climb CW","Start": "48.3km"},
    {"Route":"mayan mash","Segment": "The Grade KOM - Upper Portion","Start": "10.4km"},
    {"Route":"mech isle loop","Segment": "Mech Isle Climb CW","Start": "1.3km"},
    {"Route":"medio fondo","Segment": "Dirty Sorpresa Climb","Start": "26.8km"},
    {"Route":"medio fondo","Segment": "Epic KOM Reverse - Start to Jungle Intersection","Start": "30.9km"},
    {"Route":"medio fondo","Segment": "Jungle CCW Climb","Start": "39.9km"},
    {"Route":"medio fondo","Segment": "Jungle to Windmill Climb","Start": "43.0km"},
    {"Route":"mighty metropolitan","Segment": "East Side Sky Loop Climb","Start": "3.3km"},
    {"Route":"ocean lava cliffside loop","Segment": "Dirty Sorpresa Climb","Start": "4.9km"},
    {"Route":"ocean lava cliffside loop","Segment": "Epic KOM Reverse - Start to Jungle Intersection","Start": "9.0km"},
    {"Route":"out and back again","Segment": "Dirty Sorpresa Climb","Start": "31.7km"},
    {"Route":"park perimeter loop","Segment": "Harlem Hill Climb","Start": "3.1km"},
    {"Route":"park perimeter reverse","Segment": "East Side Drive Climb","Start": "7.0km"},
    {"Route":"petit boucle","Segment": "Les Intestins - Inbound","Start": "21.4km"},
    {"Route":"petit boucle","Segment": "Start Pens Lead-In to Petit KOM Banner","Start": "25.0km"},
    {"Route":"petit boucle","Segment": "Les Intestins - Outbound","Start": "47.7km"},
    {"Route":"petite douleur","Segment": "Les Intestins - Outbound","Start": "0.6km"},
    {"Route":"petite douleur","Segment": "Les Intestins - Outbound","Start": "14.5km"},
    {"Route":"r.g.v.","Segment": "Les Intestins - Inbound","Start": "21.4km"},
    {"Route":"richmond loop around","Segment": "E Main St Climb","Start": "15.7km"},
    {"Route":"richmond loop around","Segment": "E Main St Climb","Start": "24.8km"},
    {"Route":"richmond loop around","Segment": "Governor St Climb","Start": "41.3km"},
    {"Route":"richmond loop around","Segment": "E Main St Climb","Start": "6.5km"},
    {"Route":"richmond rollercoaster","Segment": "E Main St Climb","Start": "6.5km"},
    {"Route":"rising empire","Segment": "East Side Sky Loop Climb","Start": "3.5km"},
    {"Route":"road to ruins","Segment": "Jungle Climb","Start": "13.1km"},
    {"Route":"road to ruins","Segment": "Jungle to Windmill Climb","Start": "17.0km"},
    {"Route":"road to ruins","Segment": "Epic KOM Reverse - Start to Jungle Intersection","Start": "4.8km"},
    {"Route":"road to ruins reverse","Segment": "Jungle CCW Climb","Start": "18.1km"},
    {"Route":"road to ruins reverse","Segment": "Dirty Sorpresa Climb","Start": "4.9km"},
    {"Route":"road to ruins reverse","Segment": "Epic KOM Reverse - Start to Jungle Intersection","Start": "8.9km"},
    {"Route":"rolling highlands","Segment": "Castle Loop Climb","Start": "12.05km"},
    {"Route":"roule ma poule","Segment": "Start Pens Lead-In to Petit KOM Banner","Start": "0.0km"},
    {"Route":"roule ma poule","Segment": "Start Pens Lead-In to Petit KOM Banner","Start": "23.1km"},
    {"Route":"royal pump room 8","Segment": "Pot Bank Climb","Start": "22.25km"},
    {"Route":"royal pump room 8","Segment": "Otley Road Kicker (West Bound)","Start": "24.9km"},
    {"Route":"serpentine 8","Segment": "Jungle Climb","Start": "17.5km"},
    {"Route":"serpentine 8","Segment": "Jungle CCW Climb","Start": "8.1km"},
    {"Route":"snowman","Segment": "The Grade KOM - Upper Portion","Start": "28.7km"},
    {"Route":"snowman","Segment": "Epic KOM - Start to Bypass Intersection","Start": "9.1km"},
    {"Route":"spiral into the volcano","Segment": "Dirty Sorpresa Climb","Start": "30.4km"},
    {"Route":"spiral into the volcano","Segment": "Dirty Sorpresa Climb","Start": "4.9km"},
    {"Route":"spiral into the volcano","Segment": "Dirty Sorpresa Climb","Start": "42.8km"},
    {"Route":"sugar cookie","Segment": "Epic KOM - Start to Bypass Intersection","Start": "27.9km"},
    {"Route":"suki's playground","Segment": "Suki Climb 2","Start": "15.8km"},
    {"Route":"suki's playground","Segment": "Suki Climb 1","Start": "5.5km"},
    {"Route":"surrey hills","Segment": "Box Hill Climb from Richmond Park side","Start": "21.3km"},
    {"Route":"the big ring","Segment": "Jungle CCW Climb","Start": "30.3km"},
    {"Route":"the big ring","Segment": "Jungle to Windmill Climb","Start": "33.4km"},
    {"Route":"the highline","Segment": "East Side Sky Loop Climb","Start": "3.5km"},
    {"Route":"the highline reverse","Segment": "East Side Sky Loop Climb","Start": "3.5km"},
    {"Route":"the london pretzel","Segment": "Northumberland Ave Climb","Start": "3.6km"},
    {"Route":"the london pretzel","Segment": "Northumberland Ave Climb","Start": "3.6km"},
    {"Route":"the magnificent 8","Segment": "Dirty Sorpresa Climb","Start": "4.9km"},
    {"Route":"the magnificent 8","Segment": "Ramp out of Desert","Start": "22.84km"},
    {"Route":"the mega pretzel","Segment": "Jungle CCW Climb","Start": "17.5km"},
    {"Route":"the mega pretzel","Segment": "Jungle to Windmill Climb","Start": "20.5km"},
    {"Route":"the mega pretzel","Segment": "Dirty Sorpresa Climb","Start": "4.3km"},
    {"Route":"the mega pretzel","Segment": "Dirty Sorpresa Climb","Start": "61.6km"},
    {"Route":"the mega pretzel","Segment": "Jungle Climb","Start": "91.4km"},
    {"Route":"the muckle yin","Segment": "Castle Loop Climb","Start": "12.8km"},
    {"Route":"the muckle yin","Segment": "Castle Loop Climb","Start": "4.5km"},
    {"Route":"the uber pretzel","Segment": "Epic KOM Reverse - Start to Jungle Intersection","Start": "109.3km"},
    {"Route":"the uber pretzel","Segment": "Jungle CCW Climb","Start": "29.6km"},
    {"Route":"the uber pretzel","Segment": "Jungle to Windmill Climb","Start": "32.6km"},
    {"Route":"three sisters reverse","Segment": "Dirty Sorpresa Climb","Start": "15.3km"},
    {"Route":"tire-bouchon","Segment": "Start Pens Lead-In to Petit KOM Banner","Start": "0.0km"},
    {"Route":"tire-bouchon","Segment": "Start Pens Lead-In to Petit KOM Banner","Start": "61.3km"},
    {"Route":"tour of fire and ice","Segment": "Dirty Sorpresa Climb","Start": "4.3km"},
    {"Route":"tour of fire and ice","Segment": "Epic KOM Reverse - Start to Jungle Intersection","Start": "8.4km"},
    {"Route":"tour of tewit well","Segment": "Pot Bank Climb","Start": "5.5km"},
    {"Route":"tour of tewit well","Segment": "Otley Road Kicker (West Bound)","Start": "8.15km"},
    {"Route":"triple loops","Segment": "Northumberland Ave Climb","Start": "3.6km"},
    {"Route":"triple loops","Segment": "Box Hill Climb from Richmond Park side","Start": "32.9km"},
    {"Route":"turf n surf","Segment": "Festival Harbor Climb CCW","Start": "14.0km"},
    {"Route":"turf n surf","Segment": "Pain Cavern Climb","Start": "21.5km"},
    {"Route":"volcano flat reverse","Segment": "Dirty Sorpresa Climb","Start": "4.9km"},
    {"Route":"waisted 8","Segment": "Dirty Sorpresa Climb","Start": "10.1km"},
    {"Route":"yorkshire double loops","Segment": "Pot Bank Climb","Start": "5.5km"},
    {"Route":"yorkshire double loops","Segment": "Otley Road Kicker (West Bound)","Start": "8.15km"},
    {"Route":"road to ruins reverse","Segment": "Jungle to Windmill Climb","Start": "21.1km"},
    {"Route":"wandering flats","Segment": "Pen to Village Climb (Makuri)","Start": "19.8km"},
    {"Route":"makuri 40","Segment": "Pen to Village Climb (Makuri)","Start": "0.0km"},
    {"Route":"country to coastal","Segment": "Pen to Village Climb (Makuri)","Start": "0.0km"},
    {"Route":"castle to castle","Segment": "Pen to Village Climb (Makuri)","Start": "4.7km"},
    {"Route":"zg25 queen","Segment": "Dirty Sorpresa Climb","Start": "10.1km"},
    {"Route":"zg25 queen","Segment": "Epic KOM Reverse - Start to Jungle Intersection","Start": "14.0km"},
    {"Route":"zg25 queen","Segment": "The Grade KOM - Upper Portion","Start": "30.3km"},
    {"Route":"nyc kom after party","Segment": "Harlem Hill + Sky Road Climb","Start": "30.8km"},
    {"Route":"park perimeter loop","Segment": "Kicker to Park Finish","Start": "9.4km"},
    {"Route":"nyc kom after party","Segment": "Kicker to Park Finish","Start": "8.9km"},
    {"Route":"nyc kom after party","Segment": "Kicker to Park Finish","Start": "18.1km"},
    {"Route":"nyc kom after party","Segment": "Kicker to Park Finish","Start": "27.4km"},
    {"Route":"everything bagel","Segment": "Kicker to Park Finish","Start": "15.3km"},
    {"Route":"astoria line 8","Segment": "Kicker to Park Finish","Start": "11.25km"},
    {"Route":"knickerbocker","Segment": "Kicker to Park Finish","Start": "22.18km"},
    {"Route":"mighty metropolitan","Segment": "Kicker to Park Finish","Start": "19.75km"},
    {"Route":"rising empire","Segment": "Kicker to Park Finish","Start": "20.73km"},
    {"Route":"shisa shakedown","Segment": "Festival Harbor Climb CCW","Start": "1.4km"},
    {"Route":"shisa shakedown","Segment": "Pain Cavern Climb","Start": "8.7km"},
    {"Route":"shisa shakedown","Segment": "Mech Isle Climb CW","Start": "49.0km"},
    {"Route":"shisa shakedown","Segment": "Festival Harbor Climb CCW","Start": "50.6km"},
    {"Route":"shisa shakedown","Segment": "Rooftop KOM Reverse","Start": "19.2km"},
    {"Route":"railways and rooftops","Segment": "Rooftop KOM Reverse","Start": "3.8km"},
    {"Route":"chasing the sun","Segment": "Rooftop KOM Reverse","Start": "5.4km"},
    {"Route":"danger noodle","Segment": "The Esses Reverse","Start": "1.3km"},
    {"Route":"danger noodle","Segment": "The Esses","Start": "5.1km"},
    {"Route":"tick tock","Segment": "Ramp out of Desert","Start": "9.9km"},
    {"Route":"coast to coast","Segment": "Ramp out of Desert","Start": "11.8km"},
    {"Route":"outer scotland","Segment": "Castle Loop Climb","Start": "4.5km"},
    {"Route":"watopia's waistband","Segment": "Ramp out of Desert","Start": "9.8km"},
    {"Route":"makuri madness","Segment": "Mech Isle Climb CW","Start": "13.9km"},
{}]`;
        
        
export var jsonOtherClimbs = `[
{"Name":"Connector Canyon Climb","Map": "Makuri Islands","Length": "4.2km","Gain": "68m","avgGrade": "1.5%","maxGrade": "5.2%"},
{"Name":"Festival Harbor Climb CCW","Map": "Makuri Islands","Length": "2.0km","Gain": "53m","avgGrade": "2.6%","maxGrade": "5.1%"},
{"Name":"Festival Harbor Climb CW","Map": "Makuri Islands","Length": "2.5km","Gain": "54m","avgGrade": "2.1%","maxGrade": "5.7%"},
{"Name":"Mech Isle Climb CW","Map": "Makuri Islands","Length": "0.7km","Gain": "21m","avgGrade": "2.9%","maxGrade": "5.1%"},
{"Name":"Pain Cavern Climb","Map": "Makuri Islands","Length": "2.2km","Gain": "66m","avgGrade": "3%","maxGrade": "5.0%"},
{"Name":"Dirty Sorpresa Climb","Map": "Watopia","Length": "0.6km","Gain": "10m","avgGrade": "1.7%","maxGrade": "2.8%"},
{"Name":"Epic KOM - Start to Bypass Intersection","Map": "Watopia","Length": "1.9km ","Gain": "91m","avgGrade": "4.8%","maxGrade": "8.6%"},
{"Name":"Epic KOM Reverse - Start to Jungle Intersection","Map": "Watopia","Length": "1.2km","Gain": "67m","avgGrade": "5.7%","maxGrade": "9.6%"},
{"Name":"The Grade KOM - Upper Portion","Map": "Watopia","Length": "2.1km","Gain": "184m","avgGrade": "8.7%","maxGrade": "12.9%"},
{"Name":"Climb up from Oak Beck","Map": "Yorkshire","Length": "1.2km","Gain": "46m","avgGrade": "3.9%","maxGrade": "7.5%"},
{"Name":"Kent Rd Climb to Sprint Banner","Map": "Yorkshire","Length": "1.1km","Gain": "30m","avgGrade": "2.6%","maxGrade": "5.6%"},
{"Name":"Pot Bank Climb","Map": "Yorkshire","Length": "0.8km","Gain": "59m","avgGrade": "7.7%","maxGrade": "13.9%"},
{"Name":"Northumberland Ave Climb","Map": "London","Length": "0.4km","Gain": "14m","avgGrade": "4.1%","maxGrade": "4.7%"},
{"Name":"Les Intestins - Outbound","Map": "France","Length": "3.0km","Gain": "31m","avgGrade": "0%","maxGrade": "4.1%"},
{"Name":"Les Intestins - Inbound","Map": "France","Length": "3.0km","Gain": "32m","avgGrade": "0%","maxGrade": "3.3%"},
{"Name":"Start Pens Lead-In to Petit KOM Banner","Map": "France","Length": "3.1km","Gain": "108m","avgGrade": "3.4%","maxGrade": "7.4%"},
{"Name":"Governor St Climb","Map": "Richmond","Length": "0.6km","Gain": "36m","avgGrade": "5.8%","maxGrade": "7.2%"},
{"Name":"E Main St Climb","Map": "Richmond","Length": "1.4km","Gain": "47m","avgGrade": "3.4%","maxGrade": "6.1%"},
{"Name":"Otley Rd Climb","Map": "Yorkshire","Length": "1.6km","Gain": "57m","avgGrade": "3.4%","maxGrade": "4.8%"},
{"Name":"Otley Road Kicker (West Bound)","Map": "Yorkshire","Length": "0.5km","Gain": "32m","avgGrade": "6.1%","maxGrade": "8.5%"},
{"Name":"Castle Loop Climb","Map": "Scotland","Length": "0.45km","Gain": "15m","avgGrade": "3.5%","maxGrade": "7.5%"},
{"Name":"Jungle Climb","Map": "Watopia","Length": "2.7km","Gain": "65m","avgGrade": "2.4%","maxGrade": "3.7%"},
{"Name":"Jungle CCW Climb","Map": "Watopia","Length": "2.8km","Gain": "59m","avgGrade": "2%","maxGrade": "4.3%"},
{"Name":"Suki Climb 1","Map": "Makuri Islands","Length": "2.5km","Gain": "71m","avgGrade": "2.6%","maxGrade": "4.7%"},
{"Name":"Suki Climb 2","Map": "Makuri Islands","Length": "1.8km","Gain": "37m","avgGrade": "1.9%","maxGrade": "4.3%"},
{"Name":"Box Hill Climb from Richmond Park side","Map": "London","Length": "3.02km","Gain": "132m","avgGrade": "4.3%","maxGrade": "7.7%"},
{"Name":"Harlem Hill Climb","Map": "New York","Length": "0.7km","Gain": "35m","avgGrade": "5.1%","maxGrade": "8.8%"},
{"Name":"East Side Drive Climb","Map": "New York","Length": "0.4km","Gain": "23m","avgGrade": "5.6%","maxGrade": "8.1%"},
{"Name":"East Side Sky Loop Climb","Map": "New York","Length": "0.7km","Gain": "43m","avgGrade": "5.8%","maxGrade": "8.4%"},
{"Name":"Petit KOM Banner to La Reine","Map": "France","Length": "12.4km","Gain": "1003m","avgGrade": "9.1%","maxGrade": "13.0%"},
{"Name":"Jungle to Windmill Climb","Map": "Watopia","Length": "1.6km","Gain": "42m","avgGrade": "2.7%","maxGrade": "4.7%"},
{"Name":"Pen to Village Climb (Makuri)","Map": "Makuri Islands","Length": "1.4km","Gain": "52m","avgGrade": "3.5%","maxGrade": "10.0%"},
{"Name":"Harlem Hill + Sky Road Climb","Map": "New York","Length": "1.24km","Gain": "57m","avgGrade": "4.6%","maxGrade": "5.8%"},
{"Name":"Kicker to Park Finish","Map": "New York","Length": "0.35km","Gain": "14m","avgGrade": "4.1%","maxGrade": "8.3km"},
{"Name":"Rooftop KOM Reverse","Map": "Makuri Islands","Length": "1.6km","Gain": "52m","avgGrade": "3.2%","maxGrade": "6.4%"},
{"Name":"The Esses Reverse","Map": "Watopia","Length": "1.5km","Gain": "21m","avgGrade": "-0.2%","maxGrade": "5.8%"},
{"Name":"The Esses","Map": "Watopia","Length": "1.5km","Gain": "24m","avgGrade": "0.2%","maxGrade": "5.4%"},
{"Name":"Ramp out of Desert","Map": "Watopia","Length": "0.88km","Gain": "15m","avgGrade": "1.7%","maxGrade": "3.0%"},
{}]`;
            
export var jsonZwiftSegments = `[
{"Name":"ventoux kom","Map": "France","Length": "19km","Gain": "1481m","avgGrade": "7.8%","maxGrade": "13.0%"},
{"Name":"alpe du zwift kom","Map": "Watopia","Length": "12.2km","Gain": "1036m","avgGrade": "8.5%","maxGrade": "11.8%"},
{"Name":"epic kom","Map": "Watopia","Length": "9.5km","Gain": "415.7m","avgGrade": "3.9%","maxGrade": "8.3%"},
{"Name":"epic kom reverse","Map": "Watopia","Length": "6.3km","Gain": "402.6m","avgGrade": "5.9%","maxGrade": "10.8%"},
{"Name":"innsbruck kom","Map": "Innsbruck","Length": "7.4km","Gain": "399.9m","avgGrade": "5.4%","maxGrade": "10.4%"},
{"Name":"innsbruck kom reverse","Map": "Innsbruck","Length": "5.8km","Gain": "396.8m","avgGrade": "6.9%","maxGrade": "14.4%"},
{"Name":"the grade kom","Map": "Watopia","Length": "3.52km","Gain": "305m","avgGrade": "8.6%","maxGrade": "13.2%"},
{"Name":"keith hill kom","Map": "London","Length": "4.3km","Gain": "225.2m","avgGrade": "5.2%","maxGrade": "10.8%"},
{"Name":"radio tower kom","Map": "Watopia","Length": "1.16km","Gain": "150m","avgGrade": "12.8%","maxGrade": "16.1%"},
{"Name":"box hill kom","Map": "London","Length": "3km","Gain": "134.7m","avgGrade": "4.4%","maxGrade": "7.7%"},
{"Name":"leith hill kom","Map": "London","Length": "1.9km","Gain": "132.6m","avgGrade": "6.9%","maxGrade": "11.4%"},
{"Name":"volcano kom","Map": "Watopia","Length": "3.8km","Gain": "128.6m","avgGrade": "3.2%","maxGrade": "8.8%"},
{"Name":"fox hill kom","Map": "London","Length": "2.4km","Gain": "120.7m","avgGrade": "4.3%","maxGrade": "11.7%"},
{"Name":"petit kom","Map": "France","Length": "2.7km","Gain": "105.2m","avgGrade": "3.9%","maxGrade": "9.4%"},
{"Name":"temple kom","Map": "Makuri Islands","Length": "2.5km","Gain": "99.4m","avgGrade": "3.6%","maxGrade": "7.3%"},
{"Name":"itza kom","Map": "Watopia","Length": "3.75km","Gain": "95m","avgGrade": "2%","maxGrade": "10.0%"},
{"Name":"new york kom reverse","Map": "New York","Length": "1.1km","Gain": "89m","avgGrade": "8.1%","maxGrade": "13.0%"},
{"Name":"new york kom","Map": "New York","Length": "1.4km","Gain": "88.7m","avgGrade": "6.3%","maxGrade": "17.0%"},
{"Name":"temple kom reverse","Map": "Makuri Islands","Length": "1.9km","Gain": "68m","avgGrade": "3.5%","maxGrade": "7.8%"},
{"Name":"castle kom","Map": "Makuri Islands","Length": "2.5km","Gain": "66.4m","avgGrade": "2.1%","maxGrade": "6.3%"},
{"Name":"yorkshire kom","Map": "Yorkshire","Length": "1.2km","Gain": "65.8m","avgGrade": "5.5%","maxGrade": "6.9%"},
{"Name":"mayan mountainside kom","Map": "Watopia","Length": "1.99km","Gain": "62m","avgGrade": "3.1%","maxGrade": "5.0%"},
{"Name":"titans grove kom","Map": "Watopia","Length": "2.6km","Gain": "59.4m","avgGrade": "2.2%","maxGrade": "3.8%"},
{"Name":"sgurr summit north","Map": "Scotland","Length": "1.6km","Gain": "59m","avgGrade": "3.7%","maxGrade": "7.9%"},
{"Name":"hilly kom reverse","Map": "Watopia","Length": "2.4km","Gain": "55.8m","avgGrade": "2%","maxGrade": "8.2%"},
{"Name":"zwift kom reverse","Map": "Watopia","Length": "2.4km","Gain": "55.8m","avgGrade": "2%","maxGrade": "8.2%"},
{"Name":"rooftop kom","Map": "Makuri Islands","Length": "1.9km","Gain": "53.6m","avgGrade": "2.7%","maxGrade": "5.0%"},
{"Name":"hilly kom","Map": "Watopia","Length": "900m","Gain": "50.9m","avgGrade": "5.5%","maxGrade": "8.2%"},
{"Name":"zwift kom","Map": "Watopia","Length": "900m","Gain": "50.9m","avgGrade": "5.5%","maxGrade": "8.2%"},
{"Name":"yorkshire kom reverse","Map": "Yorkshire","Length": "1.2km","Gain": "47.9m","avgGrade": "4%","maxGrade": "6.7%"},
{"Name":"jarvis kom reverse","Map": "Watopia","Length": "1.3km","Gain": "41m","avgGrade": "3.1%","maxGrade": "9.1%"},
{"Name":"titans grove kom reverse","Map": "Watopia","Length": "890m","Gain": "39m","avgGrade": "4.4%","maxGrade": "4.8%"},
{"Name":"libby hill","Map": "Richmond","Length": "640m","Gain": "38.1m","avgGrade": "6.2%","maxGrade": "7.7%"},
{"Name":"23rd st. reverse","Map": "Richmond","Length": "1.1km","Gain": "38.1m","avgGrade": "3.5%","maxGrade": "10.3%"},
{"Name":"jarvis kom","Map": "Watopia","Length": "1.8km","Gain": "38m","avgGrade": "1.8%","maxGrade": "5.2%"},
{"Name":"sgurr summit south","Map": "Scotland","Length": "1km","Gain": "34m","avgGrade": "3.3%","maxGrade": "7.7%"},
{"Name":"leg snapper kom","Map": "Innsbruck","Length": "430m","Gain": "29.6m","avgGrade": "6.9%","maxGrade": "8.0%"},
{"Name":"libby hill kom reverse","Map": "Richmond","Length": "700m","Gain": "26.2m","avgGrade": "3.6%","maxGrade": "12.7%"},
{"Name":"23rd st. kom","Map": "Richmond","Length": "260m","Gain": "24.1m","avgGrade": "9.3%","maxGrade": "11.8%"},
{"Name":"breakaway brae","Map": "Scotland","Length": "620m","Gain": "14.6m","avgGrade": "2.4%","maxGrade": "4.5%"},
{"Name":"the clyde kicker reverse","Map": "Scotland","Length": "600m","Gain": "12m","avgGrade": "0.7%","maxGrade": "4.5%"},
{"Name":"the clyde kicker","Map": "Scotland","Length": "300m","Gain": "10.7m","avgGrade": "3.6%","maxGrade": "7.2%"},
{"Name":"aqueduc kom reverse","Map": "France","Length": "400m","Gain": "9.4m","avgGrade": "2.3%","maxGrade": "4.7%"},
{"Name":"breakaway brae reverse","Map": "Scotland","Length": "400m","Gain": "8.5m","avgGrade": "2%","maxGrade": "4.1%"},
{"Name":"aqueduc kom","Map": "France","Length": "420m","Gain": "4.9m","avgGrade": "1.16%","maxGrade": "4.4%"},
{"Name":"ny sprint reverse","Map": "New York","Length": "220m","Gain": "2m","avgGrade": "0%","maxGrade": "0.00%"},
{"Name":"ny sprint","Map": "New York","Length": "220m","Gain": "0m","avgGrade": "0%","maxGrade": "0.00%"},
{"Name":"stoneway sprint","Map": "Watopia","Length": "400m","Gain": "3m","avgGrade": "0.7%","maxGrade": "3.20%"},
{"Name":"stoneway sprint reverse","Map": "Watopia","Length": "400m","Gain": "3m","avgGrade": "0.4%","maxGrade": "2.20%"},
{"Name":"sasquatch sprint","Map": "Watopia","Length": "354m","Gain": "2m","avgGrade": "0.3%","maxGrade": "1.20%"},
{"Name":"sasquatch sprint reverse","Map": "Watopia","Length": "357m","Gain": "5m","avgGrade": "0.9%","maxGrade": "2.20%"},
{"Name":"woodland sprint","Map": "Watopia","Length": "502m","Gain": "0m","avgGrade": "0%","maxGrade": "0.00%"},
{"Name":"woodland sprint reverse","Map": "Watopia","Length": "495m","Gain": "0m","avgGrade": "-1.7%","maxGrade": "0.00%"},
{"Name":"acropolis sprint","Map": "Watopia","Length": "450m","Gain": "3m","avgGrade": "0.7%","maxGrade": "1.60%"},
{"Name":"acropolis sprint reverse","Map": "Watopia","Length": "452m","Gain": "0m","avgGrade": "-1.1%","maxGrade": "0.00%"},
{"Name":"dos d'âne sprint reverse","Map": "France","Length": "760m","Gain": "13m","avgGrade": "1.4%","maxGrade": "2.9%"},
{"Name":"sprint du cratère reverse","Map": "France","Length": "300m","Gain": "0m","avgGrade": "0.1%","maxGrade": "0.3%"},
{"Name":"sprinteur sprint reverse","Map": "France","Length": "240m","Gain": "0m","avgGrade": "0%","maxGrade": "0.00%"},
{"Name":"dos d'âne sprint","Map": "France","Length": "750m","Gain": "11m","avgGrade": "0.8%","maxGrade": "2.8%"},
{"Name":"sprinteur sprint","Map": "France","Length": "260m","Gain": "1m","avgGrade": "0.2%","maxGrade": "0.5%"},
{"Name":"sprint du cratère","Map": "France","Length": "300m","Gain": "0m","avgGrade": "0%","maxGrade": "0.00%"},
{}]`;

export var jsonTerrain = `[
    {"Name":"time trial lap","Terrain": "Hilly","World": "Bologna"},
    {"Name":"bell lap","Terrain": "Flat","World": "Crit City"},
    {"Name":"downtown dolphin","Terrain": "Flat","World": "Crit City"},
    {"Name":"casse-pattes","Terrain": "Hilly","World": "France"},
    {"Name":"douce france","Terrain": "Flat","World": "France"},
    {"Name":"france classic fondo","Terrain": "Hilly","World": "France"},
    {"Name":"la reine","Terrain": "Mountainous","World": "France"},
    {"Name":"petit boucle","Terrain": "Hilly","World": "France"},
    {"Name":"petite douleur","Terrain": "Hilly","World": "France"},
    {"Name":"r.g.v.","Terrain": "Flat","World": "France"},
    {"Name":"roule ma poule","Terrain": "Hilly","World": "France"},
    {"Name":"tire-bouchon","Terrain": "Hilly","World": "France"},
    {"Name":"ven-top","Terrain": "Mountainous","World": "France"},
    {"Name":"gravel mountain","Terrain": "Hilly","World": "Gravel Mountain"},
    {"Name":"gravel mountain reverse","Terrain": "Hilly","World": "Gravel Mountain"},
    {"Name":"2018 uci worlds course short lap","Terrain": "Mountainous","World": "Innsbruck"},
    {"Name":"achterbahn","Terrain": "Mountainous","World": "Innsbruck"},
    {"Name":"innsbruck continentals hill climb","Terrain": "Mountainous","World": "Innsbruck"},
    {"Name":"innsbruck kom after party","Terrain": "Mountainous","World": "Innsbruck"},
    {"Name":"innsbruckring","Terrain": "Flat","World": "Innsbruck"},
    {"Name":"lutscher","Terrain": "Mountainous","World": "Innsbruck"},
    {"Name":"lutscher ccw","Terrain": "Mountainous","World": "Innsbruck"},
    {"Name":"classique","Terrain": "Flat","World": "London"},
    {"Name":"classique reverse","Terrain": "Flat","World": "London"},
    {"Name":"greater london 8","Terrain": "Hilly","World": "London"},
    {"Name":"greater london flat","Terrain": "Flat","World": "London"},
    {"Name":"greater london loop","Terrain": "Hilly","World": "London"},
    {"Name":"greater london loop reverse","Terrain": "Hilly","World": "London"},
    {"Name":"greatest london flat","Terrain": "Flat","World": "London"},
    {"Name":"greatest london loop","Terrain": "Hilly","World": "London"},
    {"Name":"greatest london loop reverse","Terrain": "Hilly","World": "London"},
    {"Name":"keith hill after party","Terrain": "Hilly","World": "London"},
    {"Name":"leith hill after party","Terrain": "Hilly","World": "London"},
    {"Name":"london 8","Terrain": "Hilly","World": "London"},
    {"Name":"london 8 reverse","Terrain": "Hilly","World": "London"},
    {"Name":"london flat","Terrain": "Flat","World": "London"},
    {"Name":"london loop","Terrain": "Hilly","World": "London"},
    {"Name":"london loop reverse","Terrain": "Hilly","World": "London"},
    {"Name":"london uprising","Terrain": "Hilly","World": "London"},
    {"Name":"surrey hills","Terrain": "Hilly","World": "London"},
    {"Name":"the london pretzel","Terrain": "Hilly","World": "London"},
    {"Name":"the prl full","Terrain": "Hilly","World": "London"},
    {"Name":"the prl half","Terrain": "Hilly","World": "London"},
    {"Name":"triple loops","Terrain": "Hilly","World": "London"},
    {"Name":"bridges and boardwalks","Terrain": "Rolling","World": "Makuri Islands"},
    {"Name":"castle crit","Terrain": "Rolling","World": "Makuri Islands"},
    {"Name":"castle crit run","Terrain": "Flat","World": "Makuri Islands"},
    {"Name":"castle to castle","Terrain": "Rolling","World": "Makuri Islands"},
    {"Name":"chain chomper","Terrain": "Hilly","World": "Makuri Islands"},
    {"Name":"chasing the sun","Terrain": "Hilly","World": "Makuri Islands"},
    {"Name":"country to coastal","Terrain": "Rolling","World": "Makuri Islands"},
    {"Name":"countryside tour","Terrain": "Hilly","World": "Makuri Islands"},
    {"Name":"electric loop","Terrain": "Flat","World": "Makuri Islands"},
    {"Name":"farmland loop","Terrain": "Flat","World": "Makuri Islands"},
    {"Name":"fine and sandy","Terrain": "Rolling","World": "Makuri Islands"},
    {"Name":"flatland loop","Terrain": "Rolling","World": "Makuri Islands"},
    {"Name":"island hopper","Terrain": "Hilly","World": "Makuri Islands"},
    {"Name":"island outskirts","Terrain": "Hilly","World": "Makuri Islands"},
    {"Name":"kappa quest","Terrain": "Hilly","World": "Makuri Islands"},
    {"Name":"kappa quest reverse","Terrain": "Hilly","World": "Makuri Islands"},
    {"Name":"makuri 40","Terrain": "Rolling","World": "Makuri Islands"},
    {"Name":"makuri madness","Terrain": "Flat","World": "Makuri Islands"},
    {"Name":"makuri pretzel","Terrain": "Rolling","World": "Makuri Islands"},
    {"Name":"mech isle loop","Terrain": "Flat","World": "Makuri Islands"},
    {"Name":"neokyo all-nighter","Terrain": "Rolling","World": "Makuri Islands"},
    {"Name":"neokyo crit course","Terrain": "Flat","World": "Makuri Islands"},
    {"Name":"neon after party","Terrain": "Flat","World": "Makuri Islands"},
    {"Name":"neon flats","Terrain": "Flat","World": "Makuri Islands"},
    {"Name":"railways and rooftops","Terrain": "Rolling","World": "Makuri Islands"},
    {"Name":"rooftop rendezvous","Terrain": "Rolling","World": "Makuri Islands"},
    {"Name":"sea to tree","Terrain": "Hilly","World": "Makuri Islands"},
    {"Name":"shisa shakedown","Terrain": "Hilly","World": "Makuri Islands"},
    {"Name":"sleepless city","Terrain": "Flat","World": "Makuri Islands"},
    {"Name":"spirit forest","Terrain": "Hilly","World": "Makuri Islands"},
    {"Name":"sprinter's playground","Terrain": "Flat","World": "Makuri Islands"},
    {"Name":"suki's playground","Terrain": "Rolling","World": "Makuri Islands"},
    {"Name":"temples and towers","Terrain": "Hilly","World": "Makuri Islands"},
    {"Name":"three village loop","Terrain": "Rolling","World": "Makuri Islands"},
    {"Name":"turf n surf","Terrain": "Rolling","World": "Makuri Islands"},
    {"Name":"twilight harbor","Terrain": "Flat","World": "Makuri Islands"},
    {"Name":"two village loop","Terrain": "Rolling","World": "Makuri Islands"},
    {"Name":"valley to mountaintop","Terrain": "Hilly","World": "Makuri Islands"},
    {"Name":"wandering flats","Terrain": "Rolling","World": "Makuri Islands"},
    {"Name":"2022 cycling esports world championships route","Terrain": "Hilly","World": "New York"},
    {"Name":"astoria line 8","Terrain": "Rolling","World": "New York"},
    {"Name":"everything bagel","Terrain": "Hilly","World": "New York"},
    {"Name":"gotham grind","Terrain": "Rolling","World": "New York"},
    {"Name":"gotham grind reverse","Terrain": "Rolling","World": "New York"},
    {"Name":"grand central circuit","Terrain": "Hilly","World": "New York"},
    {"Name":"grand central circuit reverse","Terrain": "Hilly","World": "New York"},
    {"Name":"knickerbocker","Terrain": "Hilly","World": "New York"},
    {"Name":"knickerbocker reverse","Terrain": "Hilly","World": "New York"},
    {"Name":"la guardia after party","Terrain": "Hilly","World": "New York"},
    {"Name":"laguardia loop","Terrain": "Rolling","World": "New York"},
    {"Name":"laguardia loop reverse","Terrain": "Rolling","World": "New York"},
    {"Name":"lady liberty","Terrain": "Hilly","World": "New York"},
    {"Name":"mighty metropolitan","Terrain": "Hilly","World": "New York"},
    {"Name":"nyc kom after party","Terrain": "Hilly","World": "New York"},
    {"Name":"park perimeter loop","Terrain": "Rolling","World": "New York"},
    {"Name":"park perimeter reverse","Terrain": "Rolling","World": "New York"},
    {"Name":"rising empire","Terrain": "Hilly","World": "New York"},
    {"Name":"the 6 train","Terrain": "Rolling","World": "New York"},
    {"Name":"the 6 train reverse","Terrain": "Rolling","World": "New York"},
    {"Name":"the highline","Terrain": "Hilly","World": "New York"},
    {"Name":"the highline reverse","Terrain": "Hilly","World": "New York"},
    {"Name":"champs-elysees","Terrain": "Flat","World": "Paris"},
    {"Name":"lutece express","Terrain": "Flat","World": "Paris"},
    {"Name":"2015 uci worlds course","Terrain": "Rolling","World": "Richmond"},
    {"Name":"cobbled climbs","Terrain": "Rolling","World": "Richmond"},
    {"Name":"cobbled climbs reverse","Terrain": "Rolling","World": "Richmond"},
    {"Name":"libby hill after party","Terrain": "Rolling","World": "Richmond"},
    {"Name":"richmond loop around","Terrain": "Rolling","World": "Richmond"},
    {"Name":"richmond rollercoaster","Terrain": "Flat","World": "Richmond"},
    {"Name":"richmond uci reverse","Terrain": "Rolling","World": "Richmond"},
    {"Name":"the fan flats","Terrain": "Flat","World": "Richmond"},
    {"Name":"braekfast crits and grits","Terrain": "Hilly","World": "Scotland"},
    {"Name":"city and the sgurr","Terrain": "Hilly","World": "Scotland"},
    {"Name":"glasgow crit circuit","Terrain": "Rolling","World": "Scotland"},
    {"Name":"glasgow reverse","Terrain": "Rolling","World": "Scotland"},
    {"Name":"loch loop","Terrain": "Rolling","World": "Scotland"},
    {"Name":"outer scotland","Terrain": "Rolling","World": "Scotland"},
    {"Name":"rolling highlands","Terrain": "Rolling","World": "Scotland"},
    {"Name":"scotland smash","Terrain": "Rolling","World": "Scotland"},
    {"Name":"the muckle yin","Terrain": "Hilly","World": "Scotland"},
    {"Name":"2022 bambino fondo","Terrain": "Hilly","World": "Watopia"},
    {"Name":"2022 gran fondo","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"2022 medio fondo","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"accelerate to elevate","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"bambino fondo","Terrain": "Hilly","World": "Watopia"},
    {"Name":"beach island loop","Terrain": "Flat","World": "Watopia"},
    {"Name":"big flat 8","Terrain": "Flat","World": "Watopia"},
    {"Name":"big foot hills","Terrain": "Hilly","World": "Watopia"},
    {"Name":"big loop","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"big loop reverse","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"bigger loop","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"canopies and coastlines","Terrain": "Rolling","World": "Watopia"},
    {"Name":"climber's gambit","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"coast crusher","Terrain": "Flat","World": "Watopia"},
    {"Name":"coast to coast","Terrain": "Flat","World": "Watopia"},
    {"Name":"coastal crown loop","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"deca dash","Terrain": "Hilly","World": "Watopia"},
    {"Name":"downtown titans","Terrain": "Hilly","World": "Watopia"},
    {"Name":"dust in the wind","Terrain": "Hilly","World": "Watopia"},
    {"Name":"eastern eight","Terrain": "Rolling","World": "Watopia"},
    {"Name":"elevation evaluation","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"figure 8","Terrain": "Rolling","World": "Watopia"},
    {"Name":"figure 8 reverse","Terrain": "Rolling","World": "Watopia"},
    {"Name":"flat route","Terrain": "Flat","World": "Watopia"},
    {"Name":"flat route reverse","Terrain": "Flat","World": "Watopia"},
    {"Name":"four horsemen","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"glyph heights","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"going coastal","Terrain": "Flat","World": "Watopia"},
    {"Name":"gran fondo","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"handful of gravel","Terrain": "Rolling","World": "Watopia"},
    {"Name":"hilly route","Terrain": "Rolling","World": "Watopia"},
    {"Name":"hilly route reverse","Terrain": "Rolling","World": "Watopia"},
    {"Name":"itza climb finish","Terrain": "Hilly","World": "Watopia"},
    {"Name":"itza party","Terrain": "Hilly","World": "Watopia"},
    {"Name":"jungle circuit","Terrain": "Rolling","World": "Watopia"},
    {"Name":"jungle circuit reverse","Terrain": "Rolling","World": "Watopia"},
    {"Name":"jurassic coast","Terrain": "Rolling","World": "Watopia"},
    {"Name":"legends and lava","Terrain": "Hilly","World": "Watopia"},
    {"Name":"loop de loop","Terrain": "Rolling","World": "Watopia"},
    {"Name":"loopin lava","Terrain": "Rolling","World": "Watopia"},
    {"Name":"mayan 8","Terrain": "Hilly","World": "Watopia"},
    {"Name":"mayan mash","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"mayan san remo","Terrain": "Hilly","World": "Watopia"},
    {"Name":"medio fondo","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"mountain 8","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"mountain mash","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"mountain route","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"muir and the mountain","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"navig8","Terrain": "Hilly","World": "Watopia"},
    {"Name":"ocean lava cliffside loop","Terrain": "Rolling","World": "Watopia"},
    {"Name":"oh hill no","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"out and back again","Terrain": "Hilly","World": "Watopia"},
    {"Name":"peak performance","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"power to the portal","Terrain": "Rolling","World": "Watopia"},
    {"Name":"power to the tower","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"quatch quest","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"radio rendezvous","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"repack rush","Terrain": "Flat","World": "Watopia"},
    {"Name":"road to ruins","Terrain": "Rolling","World": "Watopia"},
    {"Name":"road to ruins reverse","Terrain": "Rolling","World": "Watopia"},
    {"Name":"road to sky","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"sand and sequoias","Terrain": "Hilly","World": "Watopia"},
    {"Name":"seaside sprint","Terrain": "Flat","World": "Watopia"},
    {"Name":"serpentine 8","Terrain": "Rolling","World": "Watopia"},
    {"Name":"shorelines and summits","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"snowman","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"spiral into the volcano","Terrain": "Hilly","World": "Watopia"},
    {"Name":"sugar cookie","Terrain": "Rolling","World": "Watopia"},
    {"Name":"tair dringfa fechan","Terrain": "Hilly","World": "Watopia"},
    {"Name":"temple trek","Terrain": "Flat","World": "Watopia"},
    {"Name":"tempus fugit","Terrain": "Flat","World": "Watopia"},
    {"Name":"the big ring","Terrain": "Rolling","World": "Watopia"},
    {"Name":"the classic","Terrain": "Rolling","World": "Watopia"},
    {"Name":"the magnificent 8","Terrain": "Rolling","World": "Watopia"},
    {"Name":"the mega pretzel","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"the pretzel","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"the uber pretzel","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"three little sisters","Terrain": "Hilly","World": "Watopia"},
    {"Name":"three sisters","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"three sisters reverse","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"tick tock","Terrain": "Flat","World": "Watopia"},
    {"Name":"tides and temples","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"tour of fire and ice","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"triple flat loops","Terrain": "Flat","World": "Watopia"},
    {"Name":"triple twist","Terrain": "Rolling","World": "Watopia"},
    {"Name":"two bridges loop","Terrain": "Rolling","World": "Watopia"},
    {"Name":"volcano circuit","Terrain": "Flat","World": "Watopia"},
    {"Name":"volcano circuit ccw","Terrain": "Flat","World": "Watopia"},
    {"Name":"volcano climb","Terrain": "Hilly","World": "Watopia"},
    {"Name":"volcano climb after party","Terrain": "Hilly","World": "Watopia"},
    {"Name":"volcano flat","Terrain": "Flat","World": "Watopia"},
    {"Name":"volcano flat reverse","Terrain": "Flat","World": "Watopia"},
    {"Name":"wbr climbing series","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"waisted 8","Terrain": "Flat","World": "Watopia"},
    {"Name":"watopia's waistband","Terrain": "Flat","World": "Watopia"},
    {"Name":"whole lotta lava","Terrain": "Hilly","World": "Watopia"},
    {"Name":"zwift games 2024 epic","Terrain": "Hilly","World": "Watopia"},
    {"Name":"2019 worlds harrogate circuit","Terrain": "Hilly","World": "Yorkshire"},
    {"Name":"duchy estate","Terrain": "Rolling","World": "Yorkshire"},
    {"Name":"harrogate circuit reverse","Terrain": "Hilly","World": "Yorkshire"},
    {"Name":"queen's highway","Terrain": "Rolling","World": "Yorkshire"},
    {"Name":"queen's highway after party","Terrain": "Hilly","World": "Yorkshire"},
    {"Name":"royal pump room 8","Terrain": "Hilly","World": "Yorkshire"},
    {"Name":"tour of tewit well","Terrain": "Hilly","World": "Yorkshire"},
    {"Name":"yorkshire double loops","Terrain": "Hilly","World": "Yorkshire"},
    {"Name":"danger noodle","Terrain": "Hilly","World": "Watopia"},
    {"Name":"zg25 queen","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"downtown eruption","Terrain": "Mountainous","World": "Watopia"},
    {"Name":"croissant","Terrain": "Flat","World": "France"},
    {"Name":"gentil 8","Terrain": "Rolling","World": "France"},
    {"Name":"hell of the north","Terrain": "Flat","World": "France"},
    {"Name":"bon voyage","Terrain": "Flat","World": "France"},
    {"Name":"three musketeers","Terrain": "Rolling","World": "France"},
    {"Name":"knights of the roundabout","Terrain": "Rolling","World": "France"},
    {"Name":"sacre bleu","Terrain": "Rolling","World": "France"},
{}]`;
    

export var cutTimesFlat = `[
{"min":"0","max":"27","cut": "0.06"},
{"min":"27","max":"30","cut": "0.06"},
{"min":"30","max":"33","cut": "0.06"},
{"min":"33","max":"36","cut": "0.06"},
{"min":"36","max":"39","cut": "0.07"},
{"min":"39","max":"42","cut": "0.08"},
{"min":"42","max":"45","cut": "0.09"},
{"min":"45","max":"48","cut": "0.1"},
{"min":"48","max":"99","cut": "0.11"}
]`;

export var cutTimesRolling = `[
{"min":"0","max":"27","cut": "0.08"},
{"min":"27","max":"30","cut": "0.08"},
{"min":"30","max":"33","cut": "0.08"},
{"min":"33","max":"36","cut": "0.09"},
{"min":"36","max":"39","cut": "0.1"},
{"min":"39","max":"42","cut": "0.11"},
{"min":"42","max":"45","cut": "0.12"},
{"min":"45","max":"48","cut": "0.13"},
{"min":"48","max":"99","cut": "0.13"}
]`;

export var cutTimesHilly = `[
{"min":"0","max":"27","cut": "0.1"},
{"min":"27","max":"30","cut": "0.1"},
{"min":"30","max":"33","cut": "0.11"},
{"min":"33","max":"36","cut": "0.12"},
{"min":"36","max":"39","cut": "0.13"},
{"min":"39","max":"42","cut": "0.14"},
{"min":"42","max":"45","cut": "0.15"},
{"min":"45","max":"48","cut": "0.15"},
{"min":"48","max":"99","cut": "0.15"}
]`;

export var cutTimesMountainous = `[
{"min":"0","max":"27","cut": "0.12"},
{"min":"27","max":"30","cut": "0.13"},
{"min":"30","max":"33","cut": "0.14"},
{"min":"33","max":"36","cut": "0.15"},
{"min":"36","max":"39","cut": "0.16"},
{"min":"39","max":"42","cut": "0.17"},
{"min":"42","max":"45","cut": "0.17"},
{"min":"45","max":"48","cut": "0.17"},
{"min":"48","max":"99","cut": "0.17"}
]`;
    