export var jsonNotes = `[
    {"Name":"ventoux kom","comments": ""},
    {"Name":"alpe du zwift kom","comments": ""},
    {"Name":"epic kom","comments": ""},
    {"Name":"epic kom reverse","comments": ""},
    {"Name":"innsbruck kom","comments": ""},
    {"Name":"innsbruck kom reverse","comments": ""},
    {"Name":"the grade kom","comments": ""},
    {"Name":"keith hill kom","comments": ""},
    {"Name":"radio tower kom","comments": ""},
    {"Name":"box hill kom","comments": ""},
    {"Name":"leith hill kom","comments": ""},
    {"Name":"volcano kom","comments": ""},
    {"Name":"fox hill kom","comments": ""},
    {"Name":"petit kom","comments": ""},
    {"Name":"temple kom","comments": ""},
    {"Name":"itza kom","comments": ""},
    {"Name":"new york kom reverse","comments": ""},
    {"Name":"new york kom","comments": "Not a constant grade"},
    {"Name":"temple kom reverse","comments": ""},
    {"Name":"castle kom","comments": ""},
    {"Name":"yorkshire kom","comments": ""},
    {"Name":"mayan mountainside kom","comments": ""},
    {"Name":"titans grove kom","comments": ""},
    {"Name":"sgurr summit north","comments": ""},
    {"Name":"hilly kom reverse","comments": ""},
    {"Name":"zwift kom reverse","comments": ""},
    {"Name":"rooftop kom","comments": ""},
    {"Name":"hilly kom","comments": ""},
    {"Name":"zwift kom","comments": ""},
    {"Name":"yorkshire kom reverse","comments": ""},
    {"Name":"jarvis kom reverse","comments": ""},
    {"Name":"titans grove kom reverse","comments": ""},
    {"Name":"libby hill","comments": ""},
    {"Name":"23rd st. reverse","comments": ""},
    {"Name":"jarvis kom","comments": "Kicks up before start. Watch the profile"},
    {"Name":"sgurr summit south","comments": ""},
    {"Name":"leg snapper kom","comments": ""},
    {"Name":"libby hill kom reverse","comments": ""},
    {"Name":"23rd st. kom","comments": ""},
    {"Name":"breakaway brae","comments": ""},
    {"Name":"the clyde kicker reverse","comments": ""},
    {"Name":"the clyde kicker","comments": ""},
    {"Name":"aqueduc kom reverse","comments": ""},
    {"Name":"breakaway brae reverse","comments": ""},
    {"Name":"aqueduc kom","comments": ""},
    {"Name":"ny sprint reverse","comments": "4.8% kicker after"},
    {"Name":"ny sprint","comments": "Downhill to start"},
    {"Name":"stoneway sprint","comments": "Uphill before start. Flattens 170m from Banner"},
    {"Name":"stoneway sprint reverse","comments": "Kicks up at the start then flattens with 250m to go."},
    {"Name":"sasquatch sprint","comments": "Ramp to 90m before Banner"},
    {"Name":"sasquatch sprint reverse","comments": "Downhill start. Kicks up to Banner"},
    {"Name":"woodland sprint","comments": "Downhill start.   4.1% kicker after"},
    {"Name":"woodland sprint reverse","comments": "Downhill start. Flat 200m before Banner. Kicker after"},
    {"Name":"acropolis sprint","comments": ""},
    {"Name":"acropolis sprint reverse","comments": "Flat start.  Downhill to Banner"},
    {"Name":"dos d'âne sprint reverse","comments": ""},
    {"Name":"sprint du cratère reverse","comments": ""},
    {"Name":"sprinteur sprint reverse","comments": ""},
    {"Name":"dos d'âne sprint","comments": ""},
    {"Name":"sprinteur sprint","comments": ""},
    {"Name":"sprint du cratère","comments": ""},
{"Name":"connector canyon climb","comments": ""},
{"Name":"festival harbor climb ccw","comments": "Leads to a Sprint segment"},
{"Name":"festival harbor climb cw","comments": "Leads to a Sprint segment"},
{"Name":"mech isle climb cw","comments": ""},
{"Name":"pain cavern climb","comments": ""},
{"Name":"dirty sorpresa climb","comments": ""},
{"Name":"epic kom - start to bypass intersection","comments": ""},
{"Name":"epic kom reverse - start to jungle intersection","comments": ""},
{"Name":"the grade kom - upper portion","comments": ""},
{"Name":"climb up from oak beck","comments": ""},
{"Name":"kent rd climb to sprint banner","comments": ""},
{"Name":"pot bank climb","comments": ""},
{"Name":"northumberland ave climb","comments": ""},
{"Name":"les intestins - outbound","comments": ""},
{"Name":"les intestins - inbound","comments": ""},
{"Name":"start pens lead-in to petit kom banner","comments": ""},
{"Name":"governor st climb","comments": ""},
{"Name":"e main st climb","comments": ""},
{"Name":"otley rd climb","comments": ""},
{"Name":"otley road kicker (west bound)","comments": ""},
{"Name":"castle loop climb","comments": ""},
{"Name":"jungle climb","comments": ""},
{"Name":"jungle ccw climb","comments": ""},
{"Name":"suki climb 1","comments": ""},
{"Name":"suki climb 2","comments": ""},
{"Name":"box hill climb from richmond park side","comments": ""},
{"Name":"harlem hill climb","comments": ""},
{"Name":"east side drive climb","comments": ""},
{"Name":"east side sky loop climb","comments": ""},
{"Name":"petit kom banner to la reine","comments": ""},
{"Name":"jungle to windmill climb","comments": ""},
{"Name":"pen to village climb (makuri)","comments": ""},
{"Name":"harlem hill + sky road climb","comments": ""},
{"Name":"kicker to park finish","comments": "Starts easy, then kicks up."},
{"Name":"rooftop kom reverse","comments": ""},
{"Name":"the esses reverse","comments": ""},
{"Name":"the esses","comments": ""},
{"Name":"ramp out of desert","comments": "Can split up riders"},
{}]`;
    